
services:
  mysql:
    image: mysql:8.0
    container_name: genosentinel-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: Sebasleak28
      MYSQL_DATABASE: genosentinel
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docs/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - genosentinel-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-pSebasleak28"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:
    driver: local

networks:
  genosentinel-network:
    driver: bridge